# 11-01-2023 | DAY 12 | Numpy Library Part - 1

In [1]:
import numpy as np 


In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [4]:
# tupple
arr = np.array((1,2,3,4,5,6,7,8,9,10))
print(arr)
print(type(arr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


# Dimentsion in array

In [6]:
arr = np.array(42)
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


# 1D ARRAY

In [7]:
# 1D array

arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(type(arr))
print(arr.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
1


# 2D ARRAY

In [8]:
# 2D array

arr = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(arr)
print(type(arr))
print(arr.ndim)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
<class 'numpy.ndarray'>
2


# 3D ARRAY

In [9]:
# 3D array

arr = np.array([[[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]],[[21,22,23,24,25,26,27,28,29,30],[31,32,33,34,35,36,37,38,39,40]]])
print(arr)
print(type(arr))
print(arr.ndim)


[[[ 1  2  3  4  5  6  7  8  9 10]
  [11 12 13 14 15 16 17 18 19 20]]

 [[21 22 23 24 25 26 27 28 29 30]
  [31 32 33 34 35 36 37 38 39 40]]]
<class 'numpy.ndarray'>
3


# Higher dimensional arrays

In [10]:
 # creating an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print (arr.ndim)
print(type(arr))

[[[[[1 2 3 4]]]]]
5
<class 'numpy.ndarray'>


#   add the 1st element of row 1 and last element

In [11]:
arr = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])

print('1st element on 1st dim: ', arr[0, 0])
print('5th element on 2nd dim: ', arr[1, 4])

print("sum is ", arr[0, 0] + arr[1, 4])



1st element on 1st dim:  1
5th element on 2nd dim:  15
sum is  16
