# 11-01-2023 | DAY 13 | Numpy Library Part - 2

# Slicing of numpy

In [1]:
import numpy as np


In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:3])


[2 3]


In [4]:
# spliting
arr = np.array([1, 2, 3, 4, 5])
print(arr[::2])

newarr = np.array_split(arr, 3)
print(newarr)


[1 3 5]
[array([1, 2]), array([3, 4]), array([5])]


# slicng in 2d array

In [6]:
# # slicng in 2d array

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
print(arr[1, 1:4])


[7 8 9]


# checking datatype of array

In [7]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
print(arr.dtype)

int32


In [8]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


# creating array with a define data type

In [9]:
arr = np.array([1, 2, 3, 4, 5], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


# create an array with data type 4 bytes int

In [10]:
arr = np.array([1, 2, 3, 4, 5], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


# nUMPY ARRAY SHAPE

In [11]:
# THE SHAPE OF AN ARRAY IS THE NUMBER OF ELEMENTS IN EACH DIMENSION.

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
print(arr.shape)


(2, 5)


In [16]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 0, 1, 2]])
print(arr.shape)

(3, 4)


# join the numpy

In [17]:
# join two array

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [20]:
# join two 2d array

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

print("--------------------------------------------------")

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]
--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Splitting numpy array

In [21]:
# spliting array into 3 parts

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


# ravel & flatten


convert multidimention into 1d array

In [22]:
# convert multidimensional array into 1d array

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]


# unique function

In [25]:
k = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0,1,2])
print(k)
x = np.unique(k)
print(x)

[1 2 3 4 5 6 7 8 9 0 1 2]
[0 1 2 3 4 5 6 7 8 9]


# delete

In [26]:
# delete element from array
a = np.array([1, 2, 3, 4])
a = np.delete(a, 1)
print(a)


[1 3 4]


In [27]:
x = np.array([[1, 2, 3, 4, 5, 6, 7, 8], [9, 0, 1, 2, 3, 4, 5, 6]])
print(x)
newarr = np.delete(x, 1, axis=1)
print(newarr)

[[1 2 3 4 5 6 7 8]
 [9 0 1 2 3 4 5 6]]
[[1 3 4 5 6 7 8]
 [9 1 2 3 4 5 6]]
